#!/usr/bin/env python3
from pathlib import Path

import tomli_w
import usu

Path("pyproject.toml").write_text(
    "# autogenerated by scripts/make_pyproject.toml\n"
    + tomli_w.dumps(usu.loads(Path("pyproject.usu").read_text()))
)
